lang:                  en
title:                 "Kiran's Experimental Site"

description: 
author: kam535

accent_image:          /assets/img/freepalestine.jpg
accent_color:          rgb(79,177,186)
theme_color:           rgb(25,55,71)

metadata: 'medmanfragments'

url: 'kam535.github.io'
baseurl: '/fantastic-train'

google_fonts:          false
remote_theme: hydecorp/hydejack@v9.2.1
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-include-cache
gems:
    - jekyll-asciidoc
    - jekyll-gist
    - jekyll-paginate
    
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output

sass:
  style:               compressed
